### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by yeyeoke** [kmain4/StatusPage-UptimeRobot#2]
I noticed that the statuspage gives me the wrong time and timezone, it says EST when im in CEST. Granted, im not very experienced in webdesign but I managed to get this working except for the timezone, is there a simple variable that I might change to get it fixed?

**Comment by kmain4** [comment]
Thanks for reporting it @yeyeoke, its probably using the web servers timezone, but the EST is hard coded. I'll fix that in the next commit.

**Comment by yeyeoke** [comment]
Okay, the hardcoded part with EST was simple enough to remove. 

Would it be possible to add something like "date_default_timezone_set('Europe/Stockholm');"  to override the webservers timezone?

**Comment by kmain4** [comment]
@yeyeoke I removed EST from the master branch, but the timezone should be correct for the local client, it just isn't showing it.

**Comment by yeyeoke** [comment]
Not sure what you mean but I just tried it, and Uptime Robot shows that "Plex" went down 14.38 (correct timezone) but the statuspage shows it being 12.38.

**Comment by kmain4** [comment]
Is UptimeRobot in the correct timezone?

**Comment by yeyeoke** [comment]
Yea, just noticed that UptimeRobot doesnt support CEST. No wonder why it didnt work then! :)

**Comment by kmain4** [comment]
Sounds good. Thanks for helping!
